// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPfvSXHYSWiIAY4lyM209F-ptr_9ZggDo',
    appId: '1:95269714575:web:8167957ad0d12bba738efa',
    messagingSenderId: '95269714575',
    projectId: 'meditrack-49bf8',
    authDomain: 'meditrack-49bf8.firebaseapp.com',
    storageBucket: 'meditrack-49bf8.firebasestorage.app',
    measurementId: 'G-KK6MYPT1CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc40zSa6MJ-4vmjxhA9rwxXLHr_Mg_IDM',
    appId: '1:95269714575:android:caf1d08378c3a98a738efa',
    messagingSenderId: '95269714575',
    projectId: 'meditrack-49bf8',
    storageBucket: 'meditrack-49bf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0BGOsfH2UwB3fB1Dk-_bHrgFzAD96qzE',
    appId: '1:95269714575:ios:65d759358f2cb049738efa',
    messagingSenderId: '95269714575',
    projectId: 'meditrack-49bf8',
    storageBucket: 'meditrack-49bf8.firebasestorage.app',
    iosBundleId: 'com.example.rutasuno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0BGOsfH2UwB3fB1Dk-_bHrgFzAD96qzE',
    appId: '1:95269714575:ios:65d759358f2cb049738efa',
    messagingSenderId: '95269714575',
    projectId: 'meditrack-49bf8',
    storageBucket: 'meditrack-49bf8.firebasestorage.app',
    iosBundleId: 'com.example.rutasuno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPfvSXHYSWiIAY4lyM209F-ptr_9ZggDo',
    appId: '1:95269714575:web:159aef9f97392f7c738efa',
    messagingSenderId: '95269714575',
    projectId: 'meditrack-49bf8',
    authDomain: 'meditrack-49bf8.firebaseapp.com',
    storageBucket: 'meditrack-49bf8.firebasestorage.app',
    measurementId: 'G-NCSYJF59KS',
  );
}
